substitutions:
  linglitch: 19230 # Should be multiple of bit time --- aim for close to 25ms
  uart_tx_pin_in: 17
  lin_tx_out: 13

remote_receiver:
  - id: uart_watcher
    pin: { inverted: true, number: $uart_tx_pin_in , allow_other_uses: true }
    idle: 100ms # > 9*9.615ms
    clock_resolution: 333333 # need to decrease resolution to be able to get about 90ms pulses
    on_raw:
      then:
        - remote_transmitter.transmit_raw:
            id: lin_xmit
            code: !lambda |-
              size_t outSize = 0;
              int chunkit;

              // figure out outSize
              for (int p : x)
              {
                  chunkit=p;
                  while (chunkit>$linglitch) {
                    outSize+=2; // chunk and glitch
                    chunkit+=-$linglitch;
                  }
                  if (chunkit!=0) outSize++;
              }

              std::vector<long int> out;
              out.reserve(outSize);

              for (int p : x)
              {
                  chunkit=p;
                  while (chunkit>$linglitch) {
                    // create glitch at the end of every 2nd bit
                    out.push_back($linglitch-6);
                    out.push_back(-6);
                    chunkit+=-$linglitch;
                  }
                  if (chunkit!=0) out.push_back(chunkit);
              }

              return out;

remote_transmitter:
  - id: lin_xmit
    pin: { inverted: true, number: $lin_tx_out }
    clock_resolution: 333333
    non_blocking: true
    carrier_duty_percent: 100
